[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "git-import"
description = "Import python source from a git repository into your project"
authors = [{ name="Mohammad Zain Abbas", email="mohammadzainabbas@gmail.com" }]
readme = "README.md"
license = "MIT"
dynamic = ["version"]
keywords = ["git", "import", "source", "repository"]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"