name: 🔒 Closed issue comment
on:
  issues:
    types: [closed]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Did we solve your problem?
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Don't forget to [star](https://github.com/mohammadzainabbas/git-import) the repository!

            Stay tune for more updates. Have a nice day!
